# Copyright (c) 2026 Kantoshi Miyamura
#
# AxiomMind Safe Integration — Data Models
#
# All action proposals, policy decisions, and execution results
# are immutable, typed, and validated before use.

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Any, Optional, List
from datetime import datetime
import uuid


class ActionType(str, Enum):
    """Whitelisted action types."""
    RESTART_NODE = "restart_node"
    RELOAD_NGINX = "reload_nginx"
    RESTART_WEB = "restart_web"
    LOG_ADVISORY = "log_advisory"
    CLEANUP_LOGS = "cleanup_logs"


class PolicyDecision(str, Enum):
    """Policy engine decision."""
    APPROVE = "approve"
    REJECT = "reject"
    DEFER = "defer"


class AuditEventType(str, Enum):
    """Audit log entry types."""
    ANOMALY_DETECTED = "anomaly_detected"
    ACTION_PROPOSED = "action_proposed"
    ACTION_APPROVED = "action_approved"
    ACTION_REJECTED = "action_rejected"
    ACTION_EXECUTED = "action_executed"
    ACTION_FAILED = "action_failed"
    AUDIT_TAMPER_DETECTED = "audit_tamper_detected"


class AIMode(str, Enum):
    """AxiomMind intelligence modes."""
    LOCAL_ONLY = "local_only"               # No external calls, full local intelligence
    HYBRID = "hybrid"                        # Try external LLM, fallback to local
    EXTERNAL_DISABLED = "external_disabled"  # External available but disabled


# ─────────────────────────────────────────────────────────────────────────────
# Action Proposals
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ActionProposal:
    """
    An immutable proposal to execute an action.

    Generated by mind-core when anomaly detected.
    Validated by mind-policy before execution.
    Executed by mind-executor only if approved.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=lambda: datetime.utcnow().timestamp())
    action_type: ActionType = ActionType.RESTART_NODE
    reason: str = "RPC unresponsive"
    severity: str = "critical"  # critical, warning, info
    details: Dict[str, Any] = field(default_factory=dict)

    def __hash__(self):
        return hash(self.id)


# ─────────────────────────────────────────────────────────────────────────────
# Policy Validation Results
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class PolicyDecisionResult:
    """
    Immutable result of policy validation.

    mind-policy generates this before execution.
    mind-executor checks this before running action.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=lambda: datetime.utcnow().timestamp())
    proposal_id: str = ""
    decision: PolicyDecision = PolicyDecision.REJECT
    reason: str = "Policy validation failed"

    # Conditions that passed/failed
    checks: Dict[str, bool] = field(default_factory=dict)  # {check_name: passed}

    # Metadata
    actor: str = "mind-policy"
    latency_ms: float = 0.0


@dataclass(frozen=True)
class ExecutionResult:
    """
    Immutable result of action execution.

    mind-executor records this immediately after running action.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=lambda: datetime.utcnow().timestamp())
    proposal_id: str = ""
    action_type: ActionType = ActionType.RESTART_NODE
    success: bool = False
    duration_seconds: float = 0.0
    return_code: int = 0
    stdout: str = ""
    stderr: str = ""
    error: Optional[str] = None

    # Metadata
    actor: str = "mind-executor"
    executor_version: str = "1.0"


# ─────────────────────────────────────────────────────────────────────────────
# Audit Log Entries
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class AuditEntry:
    """
    Immutable audit log entry with tamper-proof signature.

    Recorded for every decision and action.
    HMAC-SHA256 signature prevents tampering.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=lambda: datetime.utcnow().timestamp())
    event_type: AuditEventType = AuditEventType.ACTION_PROPOSED
    actor: str = "mind-core"
    action_type: Optional[ActionType] = None
    reason: str = ""

    # Links to related entries
    proposal_id: Optional[str] = None
    policy_decision_id: Optional[str] = None
    execution_id: Optional[str] = None

    # Detailed data
    details: Dict[str, Any] = field(default_factory=dict)

    # Security: HMAC-SHA256 signature (computed after all fields set)
    signature: str = ""

    def __hash__(self):
        return hash(self.id)


# ─────────────────────────────────────────────────────────────────────────────
# Health Check Results
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class HealthCheckResult:
    """
    Immutable result of a single health check.

    Used by mind-core to detect anomalies.
    Used by mind-policy to validate action preconditions.
    """
    check_name: str = "rpc_alive"
    passed: bool = False
    timestamp: float = field(default_factory=lambda: datetime.utcnow().timestamp())
    value: Any = None  # The measured value
    expected: Any = None  # The expected value
    error: Optional[str] = None  # If check failed unexpectedly


@dataclass(frozen=True)
class SystemState:
    """
    Immutable snapshot of system health at a point in time.

    Used to make decisions about action proposals.
    """
    timestamp: float = field(default_factory=lambda: datetime.utcnow().timestamp())

    # Blockchain
    rpc_alive: bool = False
    best_height: int = 0
    height_last_updated: float = 0.0
    peer_count: int = 0

    # Mempool
    tx_count: int = 0
    mempool_size_mb: float = 0.0
    fee_p50: float = 0.0
    fee_p90: float = 0.0

    # System
    disk_percent: float = 0.0
    memory_percent: float = 0.0
    cpu_percent: float = 0.0

    # Services
    nginx_active: bool = False
    axiom_web_online: bool = False


# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class MinCooldownConfig:
    """Minimum time between repeated actions (seconds)."""
    restart_node: int = 300      # 5 min
    reload_nginx: int = 180      # 3 min
    restart_web: int = 180       # 3 min
    log_advisory: int = 60       # 1 min
    cleanup_logs: int = 3600     # 1 hour


@dataclass
class RateLimitConfig:
    """Rate limiting for all actions."""
    max_actions_per_hour: int = 10
    max_restarts_per_6h: int = 3
    max_log_advisories_per_hour: int = 50


@dataclass
class ExecutorConfig:
    """Safe executor configuration."""
    command_timeout_seconds: int = 30
    enable_execution: bool = True  # Can disable for dry-run mode
    require_policy_approval: bool = True
    log_all_commands: bool = True
