// Copyright (c) 2026 Kantoshi Miyamura

use serde::{Deserialize, Serialize};

/// Severity of an agent-generated alert
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

/// An alert generated by the autonomous monitoring agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentAlert {
    /// UUID-like: first 16 hex chars derived from timestamp + message
    pub id: String,
    pub severity: AlertSeverity,
    /// "fee_market", "block_time", "network_health", "economic"
    pub category: String,
    pub message: String,
    /// What to do about it
    pub recommendation: String,
    pub timestamp_ms: u64,
    /// Additional structured data
    pub data: serde_json::Value,
}

/// Network health score (0.0–100.0)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkHealthScore {
    pub overall: f64,
    pub components: HealthComponents,
    pub computed_at_ms: u64,
    /// EWMA-learned baselines and fee prediction; None until enough data is collected
    #[serde(default)]
    pub adaptive_baselines: Option<AdaptiveBaselines>,
}

/// EWMA adaptive baselines computed by the ReputationRegistry
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AdaptiveBaselines {
    pub block_time_ewma: f64,
    pub peer_count_ewma: f64,
    pub mempool_ewma: f64,
    pub fee_ewma: f64,
    pub fee_prediction: u64,
    pub fee_trend: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthComponents {
    /// 0–100: based on peer count vs ideal
    pub peer_connectivity: f64,
    /// 0–100: how close to 30 s target
    pub block_time_stability: f64,
    /// 0–100: based on backlog and fee pressure
    pub mempool_health: f64,
    /// 0–100: blocks per expected interval
    pub chain_progress: f64,
}

/// Protocol parameter recommendation from the AI agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParameterRecommendation {
    /// e.g. "min_fee_rate", "mempool_max_size"
    pub parameter: String,
    pub current_value: f64,
    pub recommended_value: f64,
    /// 0.0–1.0
    pub confidence: f64,
    pub rationale: String,
    pub timestamp_ms: u64,
}

/// Full monitoring report from one analysis cycle
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitorReport {
    pub cycle_id: u64,
    pub timestamp_ms: u64,
    pub health: NetworkHealthScore,
    pub alerts: Vec<AgentAlert>,
    pub recommendations: Vec<ParameterRecommendation>,
    pub fee_analysis: FeeAnalysis,
    pub block_time_analysis: BlockTimeAnalysis,
    pub network_analysis: NetworkAnalysis,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeeAnalysis {
    pub median_fee_rate: u64,
    pub p75_fee_rate: u64,
    pub p90_fee_rate: u64,
    pub mempool_depth: usize,
    pub fee_pressure: FeePressure,
    /// blocks until mempool clears at current rate
    pub estimated_clear_time_blocks: u32,
    /// ML-predicted next fee rate (sat/byte) from online linear regression
    #[serde(default)]
    pub predicted_rate: u64,
    /// Fee trend direction: "rising", "falling", or "stable"
    #[serde(default)]
    pub trend: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FeePressure {
    /// mempool < 25% full
    Low,
    /// mempool 25–75% full
    Medium,
    /// mempool 75–90% full
    High,
    /// mempool > 90% full
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockTimeAnalysis {
    /// mean over last 20 blocks
    pub avg_block_time_secs: f64,
    pub std_dev_secs: f64,
    /// always 30.0
    pub target_secs: f64,
    pub current_difficulty: u32,
    /// H/s
    pub estimated_hashrate: f64,
    pub next_expected_block_eta_secs: f64,
    /// std_dev / mean, lower is more stable
    pub variance_coefficient: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkAnalysis {
    pub peer_count: u32,
    pub inbound_count: u32,
    pub outbound_count: u32,
    /// peer_count >= 8
    pub is_well_connected: bool,
    /// from AxiomMind / threat assessment
    pub threat_level: String,
    /// seconds since last block
    pub chain_tip_age_secs: u64,
    pub is_synced: bool,
}
