// Copyright (c) 2026 Kantoshi Miyamura

//! Bulletproof range proofs.
//!
//! Proves that a committed value lies in `[0, 2^64)` without revealing it.
//!
//! ## Why Bulletproofs
//!
//! - **No trusted setup** — unlike Groth16/PLONK, Bulletproofs require only a
//!   public random string (the generators), which are derived transparently.
//! - **Logarithmic proof size** — a 64-bit range proof is ~675 bytes, regardless
//!   of the range width.
//! - **Batch verification** — N proofs can be verified together faster than
//!   verifying each individually (roughly O(log N) extra work).
//!
//! ## Transcript domain separation
//!
//! Every proof creation and verification uses the Merlin transcript label
//! `b"axiom-range-proof-v1"` so Axiom range proofs are cryptographically
//! distinct from range proofs generated by other protocols using the same
//! Bulletproofs library.

use crate::commitment::{BlindingFactor, Commitment, generator_g, generator_h};
use crate::error::{CtError, Result};
use bulletproofs::{BulletproofGens, PedersenGens, RangeProof};
use curve25519_dalek::ristretto::{CompressedRistretto, RistrettoPoint};
use curve25519_dalek::scalar::Scalar;
use curve25519_dalek::traits::Identity;
use merlin::Transcript;
use serde::{Deserialize, Serialize};

/// Maximum outputs per confidential transaction (Bulletproofs batch limit).
pub const MAX_OUTPUTS: usize = 16;

/// Transcript label for domain separation.
const TRANSCRIPT_LABEL: &[u8] = b"axiom-range-proof-v1";

/// A Bulletproof range proof attesting that committed value ∈ [0, 2^64).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AxiomRangeProof {
    /// Serialized Bulletproof (≈675 bytes for a single 64-bit output).
    proof_bytes: Vec<u8>,
    /// Number of outputs covered by this proof.
    n_outputs: usize,
}

impl AxiomRangeProof {
    /// Generate a range proof for one or more output values.
    ///
    /// `outputs` is a slice of `(value, blinding_factor)` pairs — one per
    /// confidential output.  The number of outputs must be a power of two;
    /// pad with `(0, zero_blinding)` if necessary.
    ///
    /// Returns the proof and the corresponding Pedersen commitments
    /// (one per output), in the same order as `outputs`.
    pub fn prove(outputs: &[(u64, BlindingFactor)]) -> Result<(Self, Vec<Commitment>)> {
        if outputs.is_empty() {
            return Err(CtError::EmptyOutputs);
        }
        if outputs.len() > MAX_OUTPUTS {
            return Err(CtError::TooManyOutputs { max: MAX_OUTPUTS, count: outputs.len() });
        }

        // Pad to next power of two.
        let n = outputs.len().next_power_of_two();

        let pc_gens = axiom_pedersen_gens();
        let bp_gens = BulletproofGens::new(64, n);

        // Collect values and blindings, then pad to power-of-two length.
        let mut padded_values: Vec<u64> = outputs.iter().map(|(v, _)| *v).collect();
        let mut padded_blindings: Vec<Scalar> = outputs.iter().map(|(_, r)| *r.inner()).collect();

        while padded_values.len() < n {
            padded_values.push(0u64);
            padded_blindings.push(Scalar::zero());
        }

        let mut transcript = Transcript::new(TRANSCRIPT_LABEL);
        let (proof, committed_points) = RangeProof::prove_multiple(
            &bp_gens,
            &pc_gens,
            &mut transcript,
            &padded_values,
            &padded_blindings,
            64,
        )
        .map_err(|e| CtError::ProofGenerationFailed(e.to_string()))?;

        // Convert compressed Ristretto points → Commitment structs.
        // Only return the first `outputs.len()` — discard padding.
        let commitments: Vec<Commitment> = committed_points[..outputs.len()]
            .iter()
            .map(|c| Commitment::from_bytes(c.to_bytes()))
            .collect();

        let proof_bytes = proof.to_bytes().to_vec();

        Ok((AxiomRangeProof { proof_bytes, n_outputs: outputs.len() }, commitments))
    }

    /// Verify that all commitments in `commitments` are to values in [0, 2^64).
    ///
    /// `commitments` must be in the same order as the outputs that generated
    /// this proof.
    pub fn verify(&self, commitments: &[Commitment]) -> Result<()> {
        if commitments.len() != self.n_outputs {
            return Err(CtError::RangeProofInvalid);
        }

        let n = commitments.len().next_power_of_two();
        let pc_gens = axiom_pedersen_gens();
        let bp_gens = BulletproofGens::new(64, n);

        // Deserialize.
        let proof = RangeProof::from_bytes(&self.proof_bytes)
            .map_err(|_| CtError::RangeProofInvalid)?;

        // Build commitment list (CompressedRistretto), padding with identity.
        let mut points: Vec<CompressedRistretto> = commitments
            .iter()
            .map(|c| CompressedRistretto::from_slice(&c.to_bytes()))
            .collect();

        // Pad with the identity point (commitment to zero with zero blinding).
        let identity = RistrettoPoint::identity().compress();
        while points.len() < n {
            points.push(identity);
        }

        let mut transcript = Transcript::new(TRANSCRIPT_LABEL);
        proof
            .verify_multiple(&bp_gens, &pc_gens, &mut transcript, &points, 64)
            .map_err(|_| CtError::RangeProofInvalid)
    }

    /// Byte length of the serialized proof.
    pub fn byte_len(&self) -> usize {
        self.proof_bytes.len()
    }

    /// Serialize to wire/storage bytes using bincode.
    pub fn to_wire_bytes(&self) -> Vec<u8> {
        bincode::serde::encode_to_vec(self, bincode::config::standard())
            .expect("AxiomRangeProof serialization cannot fail")
    }

    /// Deserialize from wire bytes produced by [`to_wire_bytes`].
    pub fn from_wire_bytes(bytes: &[u8]) -> Result<Self> {
        bincode::serde::decode_from_slice(bytes, bincode::config::standard())
            .map(|(v, _)| v)
            .map_err(|_| CtError::RangeProofInvalid)
    }
}

/// Build Pedersen generators consistent with our hand-rolled commitment module.
///
/// `bulletproofs::PedersenGens` uses `B` for the value generator and
/// `B_blinding` for the blinding generator.  We set them to match our
/// `commitment::Commitment::commit()` convention: H for value, G for blinding.
fn axiom_pedersen_gens() -> PedersenGens {
    PedersenGens {
        B: generator_h(),           // value generator H
        B_blinding: generator_g(),  // blinding generator G
    }
}
