#!/usr/bin/env bash
# update-downloads-page.sh — Regenerate web/downloads.html for a published release.
#
# Reads the list of assets from the published GitHub Release and writes their
# URLs into the downloads page. No file is linked unless it actually exists on
# the release. No secrets are used: this calls public GitHub APIs via `gh`.
#
# Usage:
#   bash scripts/update-downloads-page.sh v1.0.0
#
# Requirements:
#   - gh CLI, authenticated (read-only is fine: `gh auth status`)
#   - jq on PATH
#
# Output:
#   web/downloads/<tag>/ASSET_URLS.txt   — list of URL\tFILENAME\tSHA256
#   web/downloads.html                    — patched in place (see SENTINELS below)
#
# The HTML file must contain two sentinel comments around the block to rewrite:
#     <!-- RELEASE-ASSETS:BEGIN -->
#     ...
#     <!-- RELEASE-ASSETS:END -->
# The script only replaces content between those sentinels; the rest of the
# page is left untouched.

set -euo pipefail

log() { echo "[update-downloads] $*"; }
die() { echo "[update-downloads] ERROR: $*" >&2; exit 1; }

TAG="${1:-}"
[[ -n "$TAG" ]] || die "usage: $0 <tag>   (e.g. v1.0.0)"

command -v gh >/dev/null || die "gh CLI not installed"
command -v jq >/dev/null || die "jq not installed"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/web/downloads/${TAG#v}"
mkdir -p "$OUT_DIR"

log "fetching release $TAG..."
RELEASE_JSON="$(gh release view "$TAG" --json assets,tagName,url,isDraft)"
IS_DRAFT="$(echo "$RELEASE_JSON" | jq -r '.isDraft')"
[[ "$IS_DRAFT" == "false" ]] || die "release $TAG is still a draft — publish it first"

# Download SHA256SUMS so we can embed hashes next to each link.
log "downloading SHA256SUMS..."
gh release download "$TAG" --pattern SHA256SUMS          --dir "$OUT_DIR" --clobber
gh release download "$TAG" --pattern SHA256SUMS.minisig  --dir "$OUT_DIR" --clobber || log "warn: no minisig present on release"

ASSET_URLS="$OUT_DIR/ASSET_URLS.txt"
: > "$ASSET_URLS"
echo "$RELEASE_JSON" | jq -r '.assets[] | "\(.name)\t\(.url)"' | while IFS=$'\t' read -r name url; do
    [[ -n "$name" ]] || continue
    sha="$(awk -v f="$name" '$2=="*"f || $2==f {print $1}' "$OUT_DIR/SHA256SUMS" | head -n1)"
    printf '%s\t%s\t%s\n' "$url" "$name" "${sha:-UNKNOWN}" >> "$ASSET_URLS"
done

log "assets:"
cat "$ASSET_URLS"

HTML="$REPO_ROOT/web/downloads.html"
[[ -f "$HTML" ]] || die "missing $HTML"
grep -q '<!-- RELEASE-ASSETS:BEGIN -->' "$HTML" || die "downloads.html missing sentinel <!-- RELEASE-ASSETS:BEGIN -->"
grep -q '<!-- RELEASE-ASSETS:END -->'   "$HTML" || die "downloads.html missing sentinel <!-- RELEASE-ASSETS:END -->"

TMP="$(mktemp)"
{
    awk '/<!-- RELEASE-ASSETS:BEGIN -->/{print; exit} {print}' "$HTML"
    echo "  <!-- generated by scripts/update-downloads-page.sh for $TAG -->"
    echo "  <ul class=\"release-assets\">"
    while IFS=$'\t' read -r url name sha; do
        printf '    <li><a href="%s" rel="noopener">%s</a> <code>%s</code></li>\n' "$url" "$name" "$sha"
    done < "$ASSET_URLS"
    echo "  </ul>"
    awk 'p{print} /<!-- RELEASE-ASSETS:END -->/{p=1; print}' "$HTML"
} > "$TMP"

mv "$TMP" "$HTML"
log "updated $HTML — review the diff before committing."
